# Generated by Django 5.2.1 on 2025-07-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castomuser',
            name='avatar',
            field=models.ImageField(blank=True, default='img/default_avatar.png', null=True, upload_to='profile-avatar/'),
        ),
    ]
