# Generated by Django 5.2.1 on 2025-07-12 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_alter_castomuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castomuser',
            name='avatar',
            field=models.ImageField(blank=True, default='static/img/default_avatar.png', null=True, upload_to='profile-avatar/'),
        ),
        migrations.CreateModel(
            name='Folow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='auth_system.castomuser')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='auth_system.castomuser')),
            ],
            options={
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
