# Generated by Django 5.2.4 on 2025-07-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_alter_castomuser_avatar_folow'),
    ]

    operations = [
        migrations.AddField(
            model_name='folow',
            name='switcher',
            field=models.BooleanField(default=False),
        ),
    ]
