# Generated by Django 5.2.1 on 2025-07-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_description_chatroom_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_name',
            field=models.CharField(default='room', max_length=100),
        ),
    ]
